HTTP:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
DBEXTRA:
  scale: 1
DB:
  scale: 2
SERVER:
  scale: 1
LOAD:
  scale: 1
